import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider, extendTheme, ScaleFade, Fade } from "@chakra-ui/react";
import { LayoutWithSidebar } from "../components";
import Head from "next/head";
import React from "react";
const theme = extendTheme({
  colors: {
    brand: {
      primaryBlack: "#323B5A",
      accent: "#9127E3",
      accentLight: "#ECE0F5",
      accentBlue: "#1BE3DC",
      greyPrimary: "#38383d",
      greySecondary: "#42414d",
    },
  },
  fonts: {
    heading: "Montserrat, sans-serif",
    body: "Montserrat, sans-serif",
  },
});

function MyApp({ Component, pageProps, router }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWithSidebar>
        <Fade key={router.route} in={true} unmountOnExit={true}>
          <Component {...pageProps} />
        </Fade>
      </LayoutWithSidebar>
    </ChakraProvider>
  );
}

export default MyApp;
