import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { WebSock, SidebarWithHeader } from "../components";
import styles from "../styles/Home.module.css";
import { Flex, Box, SimpleGrid, Center } from "@chakra-ui/react";
// const ws = new WebSocket("ws://194.163.167.188:8000/archway");

// ws.on('open', function open() {
//   // ws.send('');
// });
//
// ws.on('message', function message(data) {
//   console.log('received: %s', data);
// });

const Home: NextPage = () => {
  // useEffect(() => {
  //   ws.on('message', function message(data) {
  //     console.log('received: %s', data);
  //   });
  // })

  const handleClick = (e: any) => {
    // e.preventDefault()
    // ws.send('{}');
  };
  return (
    <div>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        />

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SidebarWithHeader>
          <Flex wrap="wrap" justifyContent="space-between">
            {/*<SimpleGrid columns={2} spacingX="12px" spacingY="10px">*/}
            <Box w="49%" height="390px" bg="white">
              <WebSock />
            </Box>
            <Box height="390px" w="49%">
              <SimpleGrid
                columns={2}
                spacingX="40px"
                spacingY="20px"
                fontSize="24px"
                fontWeight="bold"
              >
                <Box
                  color="white"
                  bgGradient="linear(to-tr, #1BE3DC,  #9127E3, #E332BF)"
                  boxShadow="sm"
                  height="180px"
                  borderRadius="10"
                >
                  <Center height="100%">9 234</Center>
                </Box>
                <Box
                  bg="white"
                  boxShadow="md"
                  height="180px"
                  borderRadius="10"
                  _hover={{
                    color: "white",
                    bgGradient: "linear(to-tr, #1BE3DC,  #9127E3, #E332BF)",
                  }}
                >
                  <Center height="100%">324 954</Center>
                </Box>
                <Box
                  bg="white"
                  boxShadow="md"
                  height="180px"
                  borderRadius="10"
                  _hover={{
                    color: "white",
                    bgGradient: "linear(to-tr, #1BE3DC,  #9127E3, #E332BF)",
                  }}
                >
                  <Center height="100%">112 / 155</Center>
                </Box>
                <Box
                  bg="white"
                  boxShadow="md"
                  height="180px"
                  borderRadius="10"
                  _hover={{
                    color: "white",
                    bgGradient: "linear(to-tr, #1BE3DC,  #9127E3, #E332BF)",
                  }}
                >
                  <Center height="100%">1 248</Center>
                </Box>
              </SimpleGrid>
            </Box>
            <Box bg="white" height="40vh" w="49%">
              <Center height="100%">4</Center>
            </Box>
            <Box bg="white" height="40vh" w="49%">
              <Center height="100%">3</Center>
            </Box>
          </Flex>
        </SidebarWithHeader>
      </main>
    </div>
  );
};

export default Home;

//
// <div className={styles.grid}>
//     <a href="https://nextjs.org/docs" className={styles.card}>
//     <h2>Documentation &rarr;</h2>
// <p>Find in-depth information about Next.js features and API.</p>
// </a>
//
// <a href="https://nextjs.org/learn" className={styles.card}>
//   <h2>Learn &rarr;</h2>
//   <p>Learn about Next.js in an interactive course with quizzes!</p>
// </a>
//
// <a
//     href="https://github.com/vercel/next.js/tree/canary/examples"
//     className={styles.card}
// >
//   <h2>Examples &rarr;</h2>
//   <p>Discover and deploy boilerplate example Next.js projects.</p>
// </a>
//
// <a
//     href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
// >
//   <h2>Deploy &rarr;</h2>
//   <p>
//     Instantly deploy your Next.js site to a public URL with Vercel.
//   </p>
// </a>
// </div>
